### ISSUE TITLE
Double deploy on netlify for all the branchs

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#11326]
It's related to the deploy environment

new one: https://deploy-preview-11317--polkadot.netlify.app/ahp/collection/244

original: https://deploy-preview-11317--koda-canary.netlify.app/ahp/collection/244

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/11318#issuecomment-2566997713_
            

<img width="821" alt="image" src="https://github.com/user-attachments/assets/1dd14728-f326-4886-a4eb-dab719c9ed45" />
<img width="857" alt="image" src="https://github.com/user-attachments/assets/e103dc3a-e5c8-4f76-82c9-180a483a3628" />

It looks like every PR has these double deployment. We should only keep one netlify deployment env.

@vikiival Do you have access to the netlify dashboard?

**Comment by vikiival** [comment]
Hey @Jarsen136,
Unfortunatelly I do not have access to koda-canary netlify
and because we had an issue with deploy previews I have made the "polkadot" one for the sake of testing. 

Cc @kodadot/internal-dev

**Comment by Jarsen136** [comment]
> Hey @Jarsen136, Unfortunatelly I do not have access to koda-canary netlify and because we had an issue with deploy previews I have made the "polkadot" one for the sake of testing.
> 
> Cc @kodadot/internal-dev

Got it. In this case, we need to update the CORS domain white list accordingly. (worker \ font-awesome-icon etc.)

**Comment by vikiival** [comment]
Seems like the original issue (`error decoding lambda response: error decoding lambda response: unexpected end of JSON input`) has been resolved

![Screenshot 2025-01-02 at 12 08 18](https://github.com/user-attachments/assets/da7afd8a-016d-4906-83f5-ce028577bc9a)

Since new deploy works, I am closing my deploy

![Screenshot 2025-01-02 at 12 08 50](https://github.com/user-attachments/assets/1c64baf0-a553-4666-a91a-c066721a9e27)

**Comment by Jarsen136** [comment]
We may still need to set up the preview environment on `polkadot.netlify.app`

**Comment by preschian** [comment]
Anyway, now all our Netlify deployments are failing. For this case, I'm still not sure what the root cause is. I've already tried to disable the functions on Netlify but it didn't help. 

The last error log I got is something like this:

`
ERROR  Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '@vue/compiler-dom'\nRequire stack:\n- /var/task/.netlify/functions-internal/server/server.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module '@vue/compiler-dom'","Require stack:","- /var/task/.netlify/functions-internal/server/server.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start (file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}
`

Maybe anyone has some ideas about this?

**Comment by vikiival** [comment]
Could be related to

- #11224

**Comment by roiLeo** [comment]
> Anyway, now all our Netlify deployments are failing. For this case, I'm still not sure what the root cause is. I've already tried to disable the functions on Netlify but it didn't help.
> 
> The last error log I got is something like this:
> 
> `ERROR Uncaught Exception {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '@vue/compiler-dom'\nRequire stack:\n- /var/task/.netlify/functions-internal/server/server.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module '@vue/compiler-dom'","Require stack:","- /var/task/.netlify/functions-internal/server/server.mjs"," at _loadUserApp (file:///var/runtime/index.mjs:1087:17)"," at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)"," at async start (file:///var/runtime/index.mjs:1282:23)"," at async file:///var/runtime/index.mjs:1288:1"]}`

had this issue on nft-shop project and it was a missing peer dependencie (vue & vue-router)

**Comment by vikiival** [comment]
> had this issue on nft-shop project and it was a missing peer dependencie (vue & vue-router)

No idea why but it works 
https://github.com/kodadot/nft-gallery/pull/11407/commits/89b10922a810c5a3a5d6ec5f0bb296cdd8429d96

**Comment by preschian** [comment]
Woah, thank you @roiLeo 🚀

Finally! This probably means we can upgrade our Nuxt version. In the past, when I tried to upgrade the Nuxt version, I got this error as well
