### ISSUE TITLE
Visitors see black screen on Dolphins & landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7430]
I think it's Brave browser running recent osx & brave version

![telegram-cloud-photo-size-2-5242280410136825840-y](https://github.com/kodadot/nft-gallery/assets/5887929/39bb7c59-850d-4f80-a279-2e2e6743d11e)

![telegram-cloud-photo-size-2-5242280410136825841-y](https://github.com/kodadot/nft-gallery/assets/5887929/84ba4b1a-07b8-4b9f-a173-2f9f2b0d6f12)

![telegram-cloud-photo-size-2-5242280410136825882-y](https://github.com/kodadot/nft-gallery/assets/5887929/8a549fe1-22e9-4245-aaf0-3e1325f28eee)

**Comment by daiagi** [comment]
I checked landing and dolhpins on
brave
chrome
firefox
chrome


all in order

fixed by #7420 


closing...

**Comment by yangwao** [comment]
It seems not fixed, as error is still there on nuxt

![telegram-cloud-photo-size-2-5248976908396384311-y](https://github.com/kodadot/nft-gallery/assets/5887929/0f343c29-a5ab-4eee-868e-96e40378522c)
