### ISSUE TITLE
Migration UI - 3 - Signing 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7562]
part of a bigger issue:
- #7552 

# Signing 🚥 
- new part, will be the same as with auto teleport (but in modal) 
- the reason everything is on its own page and not in the small modal is simply the space and no way of accidentally closing it and losing the progress. It's quite a lot of transactions if you decide to migrate 1k collection. 
<img width="373" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/c2f880ee-69e6-444f-a633-07c68cbecaf3">

- it's a step signing.
- here are possible events of the small sub-part 
<img width="572" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/f17064f3-8e42-4f4e-be46-031199365796">

- the parent section changes based on whether its in progress, its done, or inactive, changes between three states. 
<img width="119" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/e01e518a-6775-4689-8d61-4222f94aa006"> <img width="71" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/40ca3d0a-6073-45c6-92bc-f158cdc5435d"> <img width="120" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/bfbacaba-80c5-49d2-8155-74ab9fbf8515">

- the grey 1/4 circle is a loading wheel, please match the style as much as possible. 
- The same icons are used for the subsections. Every step is in this case one signed transaction. 
- let me give an example. 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/16f8397b-4f07-4a91-bddf-91607fc9a3f4)

- the contextual message is in this case what is changing. 
- when you cancel signing, you have the option to retry (it could say failed or canceled) 
<img width="627" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/5da95aa4-8e6b-4ea3-8eed-d280b3f565b0">

- after you finish all of this long signing, you can click on the button to finish (it's not automatic because in this signing, there are also transaction links (as you can see above)

**Comment by exezbcz** [comment]
Some changes will be made, mainly to the structure of what you are signing, and maybe some flow as well. 

don't take this issue please till we update that. 

cc @vikiival

**Comment by yangwao** [comment]
@exezbcz  where the user will see if everything was migrated successfully with on-chain checks?

**Comment by exezbcz** [comment]
> @exezbcz  where the user will see if everything was migrated successfully with on-chain checks? Like item list for example?

After each transaction is complete, you can click on the link. Once everything is completed it also works like a list of transactions. It does proceed to the congratulations before you click the complete button 

I will add more comprehensive list on the congratulations screen - list of items with status and link to tx. Thanks for feedback sir

**Comment by vikiival** [comment]
### Context

So as I wrote the migration script I found out a unpleasant truth: If user wants to presign items, he/she need to sign MANUALY EVERY SINGLE ITEM. 
As this should be as easy as possible, I found a new way

### The code

The create collectoion tx should be composed of
```ts
const nextId = weHaveACodeForThis()
const collection = getCollectionById('ksm', collectionId)

batch [
create(accountId, defaultSettings),
set_collection_metadata(nextId, collection.metadata)
set_team(nextId, KODA_BOT, accountId, accountId)
]
```

after transaction is successful the code should call an API
I will provide REST API docs after weekend.

Once API call was returned with status 200.

we need to compose another API call that sends all the required params to sign.

The return of this api call is a list of Signatures where signature is composed at least from 

```ts
{
  id: string // 99.99% will be the `${chain}-${rmrk_nft_id}`
  collection: string, // rmrk_collection_id
  chain: string, // rmrk / ksm
  sn: string, // rmrk_sn_id
  to_collection: string // Collection_id on ah(k/p)
  to_chain: string;
  to_sn: string; // future_nft_id
  data: string,
  signature: string,
  signer: string
}
```

> **Keep in mind that API returns just a list of owned nfts, other signatures are dedicated for other users**

Once you get this list of signatures we need to build a payload for tx

```ts

function createItem(api: ApiPromise, sig: Signature) {
  const preSignInfo = api.createType("PalletNftsPreSignedMint", sig.data);
  const create = api.tx.nfts.mintPreSigned(preSignInfo, {
    Ed25519: sig.signature,
  }, sig.signer);
  return create;
}

const items = signatures.map((sig) => mintPreSigned(api, sig));

batch(
  items
)
```

Once this is successful we can burn the existing nfts

Last step is to iterate over signatures one more time and build proper `system.remark` for `BURN`

so iterate over nfts build proper extrinsic (do not remeber from head so can find along the way).

Once this is done.
Call API to mark these nfts as migrated and continue to https://github.com/kodadot/nft-gallery/issues/7563

### From design

**Comment by exezbcz** [comment]
Thank you sir; mostly clear, however, ad signing txs - some questions 

For me, it's important how many tx the user will sign and after which step the user will wait. 


from what i understand: 

- you sign the first one, wait till the collection is created 
- signing the API - or giving it rights to manage items? 
- ad step 3 is there also needed a signature for every 200 items or that is handled by someone else
- step 4 - one tx for burning

cc @vikiival

**Comment by exezbcz** [comment]
@vikiival, last question just to be sure 

What will user sign if he is not the owner of the collection - migrating only items that were pre-signed by the owner

- is there min. of 2 transactions? 
- what about step two, same as with migrating as the owner of the collection?

thanks!

**Comment by vikiival** [comment]
> What will user sign if he is not the owner of the collection - migrating only items that were pre-signed by the owner

There should be a separated screen for /migrations where user can find list of waiting mogrations and can transact them in the batch

**Comment by exezbcz** [comment]
## Changes/second iteration

![image](https://github.com/kodadot/nft-gallery/assets/90852205/191b33cc-4850-4c09-b56f-b329068ee965)
- changes to copy, sections, transactions names, number of transactions.
- updated in the main flow in figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=4218%3A2062&mode=design&t=GKkayTA5Y8dTj3H1-1

### Initiation stage
![image](https://github.com/kodadot/nft-gallery/assets/90852205/5868c421-4bff-4639-8a04-473793d0468e)
- two steps
- sign collection creation
- automated step - no signing needed, just waiting, more states here: 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/daba3a35-8f7d-44b6-9d97-75f2c0133c43)
- its under the sections

------------

### Migrating your items
- that is the mentioned batch transactions, there is a limit of items that could be migrated.
- viki mentioned that there might be an additional step of unlisting all items - if it's needed to add it, do so before the three transactions in this section. 
- 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/65458d54-2c91-472e-ae92-24deaef34103)

------------

### Finalization
- the fancy name for burning items on the source chain, I did not want to mention that explicitly. 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/e51c39a3-f7e9-4e1b-a4ba-bfda68f5be82)


- rest stays the same

**Comment by vikiival** [comment]
I updated the API

**Comment by preschian** [comment]
hi @vikiival, is there something wrong with my args in here? https://assethub-kusama.subscan.io/block/0xf8cbf28ce3b0ce89b07ab484654c589efd443e6ed241902c437a59b52f920b73

I'm getting a 400 error on the `/relocations` endpoint. It returns `Cannot read properties of null (reading 'currentOwner')`

**Comment by vikiival** [comment]
For the logs purposes

> hi @vikiival, is there something wrong with my args in here? https://assethub-kusama.subscan.io/block/0xf8cbf28ce3b0ce89b07ab484654c589efd443e6ed241902c437a59b52f920b73


Everything is good here

> I'm getting a 400 error on the `/relocations` endpoint. It returns `Cannot read properties of null (reading 'currentOwner')`

There was a bug with usage of uniquery I was requesting `image` field on `rmrk` endpoint that does not exist.
Fixed and deployed

**Comment by preschian** [comment]
Updates:
- still in progress step 3, preparing pre-signed items. Currently, I still ask Viki related to the backend via Telegram
- rmrk => looks good until step 3
- ksm => sometimes, error on step 1

I will check again tomorrow

**Comment by preschian** [comment]
Updates:
- Mostly still errors on the db side. One of the issues was: https://github.com/aidenwallis/kysely-d1/issues/23
- Currently still in this phase:

![image](https://github.com/kodadot/nft-gallery/assets/734428/af6c7584-c8ce-462f-b86c-5ba454052c8d)

**Comment by preschian** [comment]
Updates https://github.com/kodadot/nft-gallery/pull/7909:

On ahk:
- ✅ create collection
- ✅ mock API on `/relocations`
- ❌ real API on `/relocations` return `D1_ERROR`
- ❌ migrate nfts from mock API https://assethub-kusama.subscan.io/extrinsic/0x8584ee95d864fc6806923eb96227afd758cd17747283f340d384318f9cc3517d

On ahp:
- ✅ create collection 
- ❌ mock API on `/relocations` returns `Target collection not found or you are not the owner`
- ❌ real API on `/relocations` return `D1_ERROR`

cc @vikiival 

Iterations and Burn not yet implemented. I will implement that once migration nfts look ok

**Comment by preschian** [comment]
Because of the API error, I will try to help on the backend side also on https://github.com/kodadot/private-workers

**Comment by vikiival** [comment]
> ❌ mock API on /relocations returns Target collection not found or you are not the owner

This was fixed

**Comment by preschian** [comment]
> Because of the API error, I will try to help on the backend side also on [kodadot/private-workers](https://github.com/kodadot/private-workers)

I'm still not able to test this out. My dashboard has been blank since yesterday. There were some issues on the Cloudflare side. ref: https://github.com/kodadot/workers/issues/192#issuecomment-1791968274

https://www.cloudflarestatus.com/

![image](https://github.com/kodadot/nft-gallery/assets/734428/abd3f80e-9dd9-446d-b2f5-2443280b87bb)

**Comment by vikiival** [comment]
Still dead :/

![Screenshot 2023-11-03 at 12 50 00](https://github.com/kodadot/nft-gallery/assets/22471030/5e61f8f0-73a1-46ad-98ea-3ae9dd5cd50e)
